further mingw64
Signed-off-by: JP Lomas <jp@theqrl.org>

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -10,8 +10,7 @@ on:
 
 env:
   BUILD_TYPE: Debug
-  WIN_LIBOQS_INSTALL_PATH: C:\liboqs
-  WIN_PKG_CONFIG_PATH: C:\Strawberry\c\lib\pkgconfig
+  WIN_LIBOQS_INSTALL_PATH: C:/liboqs
 
 jobs:
   build:
@@ -25,21 +24,35 @@ jobs:
         with:
           go-version: 1.21
 
+      - name: Set up MSYS2
+        uses: msys2/setup-msys2@v2
+        with:
+          msystem: MINGW64
+          update: true
+          install: mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-ninja mingw-w64-x86_64-pkg-config
+
       - name: Install liboqs Windows
-        shell: cmd
+        shell: msys2 {0}
         run: |
           git clone --branch main --single-branch --depth 1 https://github.com/jplomas/liboqs
-          cmake -S liboqs -B liboqs\build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.WIN_LIBOQS_INSTALL_PATH}} -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON
-          cmake --build liboqs\build --parallel 4
-          cmake --build liboqs\build --target install
+          cmake -S liboqs -B liboqs/build -G Ninja -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.WIN_LIBOQS_INSTALL_PATH}} -DBUILD_SHARED_LIBS=ON -DOQS_BUILD_ONLY_LIB=ON -DCMAKE_C_FLAGS="-D__ORDER_LITTLE_ENDIAN__=1234 -D__ORDER_BIG_ENDIAN__=4321 -D__BYTE_ORDER__=1234"
+          cmake --build liboqs/build --parallel 4
+          cmake --build liboqs/build --target install
 
       - name: Configure pkgconfig Windows
-        shell: cmd
+        shell: msys2 {0}
         run: |
-          copy .\.config\liboqs-go.pc.win64 ${{env.WIN_PKG_CONFIG_PATH}}\liboqs-go.pc
+          mkdir -p /mingw64/lib/pkgconfig
+          cp .config/liboqs-go.pc.win64 /mingw64/lib/pkgconfig/liboqs-go.pc
 
       - name: Run unit tests Windows
-        shell: cmd
+        shell: msys2 {0}
+        env:
+          CGO_ENABLED: 1
+          CC: gcc
+          PKG_CONFIG_PATH: /mingw64/lib/pkgconfig
         run: |
-          set PATH=%PATH%;${{env.WIN_LIBOQS_INSTALL_PATH}}\bin
-          go test -v -run "TestSignatureCorrectness|TestSignatureCorrectnessWithCtxStr" .\oqstests
+          export PATH="/c/liboqs/bin:$PATH"
+          # Debug: show what pkg-config finds
+          pkg-config --cflags --libs liboqs-go || echo "pkg-config failed"
+          go test -v -run "TestSignatureCorrectness|TestSignatureCorrectnessWithCtxStr" ./oqstests
